# Generated by Django 3.1.5 on 2021-01-28 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('bio', models.TextField(default='Add a bio to tell other students about yourself', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('university', models.CharField(choices=[('All Hallows College', 'All Hallows College'), ('Athlone Institute of Technology', 'Athlone Institute of Technology'), ('Carlow College', 'Carlow College'), ('Cork Institute of Technology', 'Cork Institute of Technology'), ('Dublin City University', 'Dublin City University'), ('Dun Laoghaire Institute of Art, Design and Technology', 'Dun Laoghaire Institute of Art, Design and Technology'), ('Dundalk Institute of Technology', 'Dundalk Institute of Technology'), ('Galway-Mayo Institute of Technology', 'Galway-Mayo Institute of Technology'), ('Institute of Public Administration', 'Institute of Public Administration'), ('Insitute of Technology Carlow', 'Insitute of Technology Carlow'), ('Institute of Technology Sligo', 'Insitute of Technology Sligo'), ('Institute of Technology Tralee', 'Institute of Technology Tralee'), ('Letterkenny Institute of Technology', 'Letterkenny Institute of Technology'), ('Limerick Institute of Technology', 'Limerick Institute of Technology'), ('Marino Institute of Education', 'Marino Institute of Education'), ('National University of Ireland Maynooth', 'National University of Ireland Maynooth'), ('National College of Art and Design', 'National College of Art and Design'), ('National College of Ireland', 'National College of Ireland'), ('National University of Ireland Galway', 'National University of Ireland Galway'), ('Royal College of Surgeons Ireland', 'Royal College of Surgeons Ireland'), ('Royal Irish Academy of Music', 'Royal Irish Academy of Music'), ('Saint Patricks College Maynooth', 'Saint Patricks College Maynooth'), ('Technological University Dublin', 'Technological University Dublin'), ('Trinity College Dublin', 'Trinity College Dublin'), ('University College Cork', 'University College Cork'), ('University College Dublin', 'University College Dublin'), ('University of Limerick', 'University of Limerick'), ('Waterford Institute of Technology', 'Waterford Institute of Technology')], max_length=60)),
                ('course', models.CharField(blank=True, max_length=255)),
                ('year', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], max_length=10)),
                ('profile_picture', models.ImageField(default='defaultprofilepicture.png', upload_to='profilepictures/')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Send Request', 'Send Request'), ('Accept Request', 'Accept Request')], max_length=15)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='User_Profiles.userprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='User_Profiles.userprofile')),
            ],
        ),
    ]
