# Generated by Django 3.1.5 on 2021-02-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profiles', '0006_auto_20210208_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='availability',
            field=models.TextField(default='Complete this section to tell students about your availability', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience',
            field=models.TextField(default='Complete this section to tell students about your experience', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hourly_rate',
            field=models.CharField(choices=[('€5', '€5'), ('€10', '€10'), ('€15', '€15'), ('€20', '€20'), ('€25', '€25'), ('€30', '€30'), ('€35', '€35'), ('€40', '€40')], default='€20', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qualifications',
            field=models.TextField(default='Complete this section to tell students about your qualifications', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='topics',
            field=models.TextField(default='Complete this section to tell students about what topics / subjects you cover', max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='defaultprofilepicture.png', upload_to='tutorprofilepictures/'),
        ),
    ]
