# Generated by Django 3.1.5 on 2021-02-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profiles', '0008_auto_20210208_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='availability',
            field=models.TextField(blank='True', max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='experience',
            field=models.TextField(blank='True', max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='qualifications',
            field=models.TextField(blank='True', max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='topics',
            field=models.TextField(blank='True', max_length=500),
        ),
    ]
