# Generated by Django 3.1.5 on 2021-03-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profiles', '0009_auto_20210208_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('Request Sent', 'Request Sent'), ('Request Accepted', 'Request Accepted')], max_length=30),
        ),
    ]
